[package]
name = "waddle_derive"
version = "0.0.0"
authors = ["Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
itertools = "0.12.0"
proc-macro2 = "1.0.24"
proc-quote = "0.4.0"
syn = { version = "2.0.39", features = ["full"] }
