[package]
name = "waddle_derive"
version = "0.0.0"
authors = ["Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
itertools = "0.9.0"
proc-macro2 = "1.0.24"
proc-quote = "0.3.2"
syn = { version = "1.0.54", features = ["full"] }
