[package]
name = "waddle_derive"
version = "0.0.0"
authors = ["Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
itertools = "^0.8.0"
proc-macro2 = "0.4"
proc-quote = "^0.2.1"
syn = { version = "0.15.30", features = ["full"] }
